[template]
cargo_generate_version = ">0.9.0"
ignore = [ "test-template.sh" ]

[conditional.'crate_type == "lib"']
ignore = [ "src/main.rs" ]

[conditional.'crate_type == "bin"']
ignore = [ "src/lib.rs", "benches" ]
