[package]
name = "{{crate_name}}"
version = "0.1.0"
authors = ["{{authors}}"]
description = ""
homepage = "https://github.com/danielparks/{{crate_name}}"
repository = "https://github.com/danielparks/{{crate_name}}"
readme = "README.md"
keywords = []
categories = [] # https://crates.io/category_slugs
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

{% if crate_type == "bin" -%}
[dependencies]
anyhow = "1.0.44"
log = "0.4.14"
simplelog = "0.10.2"
smol = "1.2.5"
structopt = "0.3.23"
{% endif -%}
{% if crate_type == "lib" -%}
[dev-dependencies]
assertify = { path = "/Users/daniel/projects/assertify" }
{% endif -%}
