name = "Daniel’s Simple Template"
description = "A simple template for my projects"
kickstart_version = 1

[[variables]]
name = "project_name"
default = "some_project"
prompt = "project_name:"
validation = "^([a-z][a-z0-9_]+)$"

[[variables]]
name = "author_name"
default = "Daniel Parks"
prompt = "Author name:"
validation = "\\S"

[[variables]]
name = "author_email"
default = "oss-project@demonhorse.net"
prompt = "Author email:"
validation = "^[^@ \"<>]+@[^@ \"<>]+$"

[[variables]]
name = "year"
default = "2019"
prompt = "Year:"
